// Code generated by Warden. DO NOT EDIT.

package main

import (
	warden "github.com/egsam98/warden"
	zerolog "github.com/rs/zerolog"
)

func (self *PreConfig) Validate() error {
	var errs warden.Errors
	if self.Name == "" {
		errs.Add("name", warden.Error("required"))
	}
	if self.Class == "" {
		errs.Add("class", warden.Error("required"))
	}
	errs.Add("log", func() error {
		self := &self.Log
		var errs warden.Errors
		if self.Level == 0 {
			self.Level = zerolog.InfoLevel
		}
		return errs.AsError()
	}())
	return errs.AsError()
}
